# Generated by Django 2.1.4 on 2019-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_accountgroup_clientaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(choices=[('financial_institution', 'financial_institution'), ('deposit_money', 'deposit_money'), ('old_employer_retirement', 'old_employer_retirement'), ('employer_retirement', 'employer_retirement')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
