# Generated by Django 2.1.4 on 2019-01-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190116_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='financial_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='is_pre_saved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='monthly_contributions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='monthly_distributions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='process_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='sas_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='step_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
