# Generated by Django 2.1.4 on 2019-01-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_appointedbillingspec'),
        ('client', '0007_clientaccount_system_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('account_description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Personal Investment Account'), (2, 'Joint Investment Account'), (3, 'Roth IRA'), (4, 'Traditional IRA'), (5, 'Retirement Account')], default=1)),
                ('status', models.CharField(choices=[('registered', 'registered'), ('active', 'active'), ('init rebalance', 'init rebalance'), ('init rebalance complete', 'init rebalance complete'), ('rebalanced', 'rebalanced'), ('account analyzed', 'account analyzed'), ('account closed', 'account closed'), ('waiting activation', 'waiting activation')], default='registered', max_length=50)),
                ('source', models.CharField(blank=True, default='sample', max_length=45, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('client_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.ClientAccount')),
            ],
            options={
                'db_table': 'system_client_accounts',
            },
        ),
    ]
