# Generated by Django 2.1.4 on 2019-01-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0002_cemodel'),
        ('user', '0006_user_appointedbillingspec'),
        ('client', '0008_systemaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webo_admin.CeModel')),
            ],
            options={
                'db_table': 'client_portfolio',
            },
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientAccounts', to='user.User'),
        ),
    ]
