# Generated by Django 2.1.4 on 2019-02-03 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20190203_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p7', 'New/Update Contributions'), ('p9', 'Portfolio Proposal'), ('p8', 'New/Update Distributions'), ('p6', 'Banking Information Update'), ('p2', 'Transfer'), ('p10', 'Initial Rebalance'), ('p3', 'Rollover'), ('p4', 'New/Update Beneficiary'), ('p1', 'New Account'), ('p5', 'Address Update'), ('a1', 'New Retirement Account'), ('a3', 'Closed Account')], max_length=3),
        ),
    ]
