# Generated by Django 2.1.4 on 2019-02-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20190203_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='client_status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'prospect'), (2, 'client')], null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p8', 'New/Update Distributions'), ('p7', 'New/Update Contributions'), ('p4', 'New/Update Beneficiary'), ('p2', 'Transfer'), ('p5', 'Address Update'), ('p1', 'New Account'), ('p10', 'Initial Rebalance'), ('p6', 'Banking Information Update'), ('p3', 'Rollover'), ('p9', 'Portfolio Proposal'), ('a1', 'New Retirement Account'), ('a3', 'Closed Account')], max_length=3),
        ),
    ]
