# Generated by Django 2.1.4 on 2019-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20190208_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p8', 'New/Update Distributions'), ('p4', 'New/Update Beneficiary'), ('p2', 'Transfer'), ('p6', 'Banking Information Update'), ('p1', 'New Account'), ('p7', 'New/Update Contributions'), ('p5', 'Address Update'), ('p10', 'Initial Rebalance'), ('p9', 'Portfolio Proposal'), ('p3', 'Rollover'), ('a3', 'Closed Account'), ('a1', 'New Retirement Account')], max_length=3),
        ),
    ]
