# Generated by Django 2.1.4 on 2019-02-17 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190215_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='consolidator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consolidatedAccounts', to='client.ClientAccount'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='unconsolidated',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p8', 'New/Update Distributions'), ('p9', 'Portfolio Proposal'), ('p6', 'Banking Information Update'), ('p7', 'New/Update Contributions'), ('p2', 'Transfer'), ('p1', 'New Account'), ('p10', 'Initial Rebalance'), ('p3', 'Rollover'), ('p4', 'New/Update Beneficiary'), ('p5', 'Address Update'), ('a1', 'New Retirement Account'), ('a3', 'Closed Account')], max_length=3),
        ),
    ]
