# Generated by Django 2.1.4 on 2019-03-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20190217_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='is_pre_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='unconsolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p8', 'New/Update Distributions'), ('p7', 'New/Update Contributions'), ('p4', 'New/Update Beneficiary'), ('p2', 'Transfer'), ('p10', 'Initial Rebalance'), ('p6', 'Banking Information Update'), ('p3', 'Rollover'), ('p1', 'New Account'), ('p5', 'Address Update'), ('p9', 'Portfolio Proposal'), ('a3', 'Closed Account'), ('a1', 'New Retirement Account')], max_length=3),
        ),
    ]
