# Generated by Django 2.1.4 on 2019-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20190303_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='message_code',
            field=models.CharField(choices=[('p1', 'New Account'), ('p9', 'Portfolio Proposal'), ('p2', 'Transfer'), ('p3', 'Rollover'), ('p4', 'New/Update Beneficiary'), ('p5', 'Address Update'), ('p10', 'Initial Rebalance'), ('p7', 'New/Update Contributions'), ('p6', 'Banking Information Update'), ('p8', 'New/Update Distributions'), ('a3', 'Closed Account'), ('a1', 'New Retirement Account')], max_length=3),
        ),
    ]
