# Generated by Django 2.1.4 on 2019-01-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190108_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appointedBillingSpec',
        ),
    ]
