# Generated by Django 2.1.4 on 2019-01-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_appointedbillingspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appointedBillingSpec',
        ),
    ]
