# Generated by Django 2.1.4 on 2019-01-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0001_initial'),
        ('user', '0005_remove_user_appointedbillingspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appointedBillingSpec',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='webo_admin.BillingSpec'),
            preserve_default=False,
        ),
    ]
