# Generated by Django 2.1.4 on 2019-01-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_appointedbillingspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointedBillingSpec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webo_admin.BillingSpec'),
        ),
    ]
