# Generated by Django 2.1.4 on 2019-01-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190126_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ria_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ria', to='user.User'),
        ),
    ]
