# Generated by Django 2.1.4 on 2019-01-12 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_appointedbillingspec'),
        ('ria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_withdraw_age_input', models.BooleanField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'risk_questions',
            },
        ),
    ]
