# Generated by Django 2.1.4 on 2019-01-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0002_cemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemodel',
            name='commission_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='commission_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='generous_market_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='low_market_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webo_admin.CeModel'),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='risk_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
