# Generated by Django 2.1.4 on 2019-01-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0003_auto_20190124_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemodel',
            name='type',
            field=models.IntegerField(choices=[(1, '1: Strategy type'), (2, '2: Custom type')]),
        ),
    ]
