# Generated by Django 2.1.4 on 2019-01-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_appointedbillingspec'),
        ('webo_admin', '0004_auto_20190125_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('tolerance_band', models.IntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webo_admin.CeModel')),
            ],
            options={
                'db_table': 'asset_classes',
            },
        ),
        migrations.CreateModel(
            name='CeModelEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_qualified', models.BooleanField()),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webo_admin.AssetClass')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelEntities', to='webo_admin.CeModel')),
            ],
            options={
                'db_table': 'ce_model_entities',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_performance', models.FloatField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('tolerance_band', models.IntegerField(blank=True, null=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='webo_admin.AssetClass')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='webo_admin.Subclass')),
            ],
            options={
                'db_table': 'subclasses',
            },
        ),
        migrations.AddField(
            model_name='cemodelentity',
            name='subclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceModelEntities', to='webo_admin.Subclass'),
        ),
    ]
