# Generated by Django 2.1.4 on 2019-01-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0006_auto_20190125_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingspec',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
