# Generated by Django 2.1.4 on 2019-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webo_admin', '0009_auto_20190126_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingspec',
            name='type',
            field=models.IntegerField(choices=[(1, '1: Tier'), (2, '2: Flat')]),
        ),
    ]
